/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardingHouseIdRouteImport } from './routes/boarding-house.$id'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedCustomerRouteImport } from './routes/_authenticated/customer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCustomerProfileRouteImport } from './routes/_authenticated/customer/profile'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingHouseIdRoute = BoardingHouseIdRouteImport.update({
  id: '/boarding-house/$id',
  path: '/boarding-house/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerRoute = AuthenticatedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerProfileRoute =
  AuthenticatedCustomerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customer': typeof AuthenticatedCustomerRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRoute
  '/boarding-house/$id': typeof BoardingHouseIdRoute
  '/customer/profile': typeof AuthenticatedCustomerProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customer': typeof AuthenticatedCustomerRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRoute
  '/boarding-house/$id': typeof BoardingHouseIdRoute
  '/customer/profile': typeof AuthenticatedCustomerProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/customer': typeof AuthenticatedCustomerRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/boarding-house/$id': typeof BoardingHouseIdRoute
  '/_authenticated/customer/profile': typeof AuthenticatedCustomerProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/browse'
    | '/reset-password'
    | '/admin'
    | '/customer'
    | '/owner'
    | '/boarding-house/$id'
    | '/customer/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/browse'
    | '/reset-password'
    | '/admin'
    | '/customer'
    | '/owner'
    | '/boarding-house/$id'
    | '/customer/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/browse'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/customer'
    | '/_authenticated/owner'
    | '/boarding-house/$id'
    | '/_authenticated/customer/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BoardingHouseIdRoute: typeof BoardingHouseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding-house/$id': {
      id: '/boarding-house/$id'
      path: '/boarding-house/$id'
      fullPath: '/boarding-house/$id'
      preLoaderRoute: typeof BoardingHouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer/profile': {
      id: '/_authenticated/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof AuthenticatedCustomerProfileRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
  }
}

interface AuthenticatedCustomerRouteChildren {
  AuthenticatedCustomerProfileRoute: typeof AuthenticatedCustomerProfileRoute
}

const AuthenticatedCustomerRouteChildren: AuthenticatedCustomerRouteChildren = {
  AuthenticatedCustomerProfileRoute: AuthenticatedCustomerProfileRoute,
}

const AuthenticatedCustomerRouteWithChildren =
  AuthenticatedCustomerRoute._addFileChildren(
    AuthenticatedCustomerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCustomerRoute: typeof AuthenticatedCustomerRouteWithChildren
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCustomerRoute: AuthenticatedCustomerRouteWithChildren,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BoardingHouseIdRoute: BoardingHouseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
